typography_spectrum: 0.3090449704322964
color:
  brandStrength: 0.9856115588918328
  lightness: 0.650660403072834
  saturation: 0.4910955890081823
  rhythmicContrast: 0.5112764497753233
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.22512824111618102
name: Gridnationator
title: What is the grid?
